[project]
name = "gradient-descent-visualizer"
version = "0.1.0"
author = "Lars Heimann"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"numpy>=1.26",
	"pandas>=2.1",
	"plotly>=5.24",
	"streamlit>=1.38",
]
